Revert "Merge remote-tracking branch 'origin/feature_2020_er_eligibility_r3' into enroll_uat"
This reverts commit 81564e9d92bb1e3525cc66a41140587446732ae9, reversing
changes made to 5312dd7639b47b2d719ceb583ccdcf0b65e784bf.

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -1,1 +1,8 @@
 #!/bin/sh
+echo "Running rubocop check"
+
+$GIT_DIR/../rubocop_check_pre_commit.sh
+if [[ $? -ne 0 ]]; then
+  echo "Rubocop Check FAILED"
+  exit 1
+fi
